CREATE TABLE `GUESTBOOK_MESSAGE` (
  `MESSAGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GUEST_NAME` varchar(20) DEFAULT NULL,
  `MESSAGE` text,
  `REGISTRY_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MESSAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr
